# Generated by Django 4.2.4 on 2023-08-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='mobile_number',
            new_name='phone_number',
        ),
    ]
